name: CI

on:
  push:
    paths:
      - '**.el'
      - '.github/**'
      - 'Eldev'
  pull_request:
    paths:
      - '**.el'
      - '.github/**'
      - 'Eldev'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs_version:
          - 27.1
          - 26.3
          # - 26.2
          # - 26.1
          - 25.3
          # - 25.2
          # - 25.1
          - 24.5
          - 24.4
          - snapshot
    # env:
    #   # We only generate a coverage report for one Emacs version
    #   # (generally the latest release version) in order to avoid
    #   # duplicate reports.
    #   coveralls_emacs_version: 27.1
    steps:
    - name: Set up Emacs
      uses: purcell/setup-emacs@master
      with:
        version: ${{matrix.emacs_version}}

    - name: Install Eldev
      run: curl -fsSL https://raw.github.com/doublep/eldev/master/webinstall/github-eldev | sh

    - name: Check out the source code
      uses: actions/checkout@v2

    - name: Install Elisp dependencies
      run: eldev prepare test

    - name: Run the test suite
      run: |
        eldev -p -dtT test

    - name: Run the test suite in source mode (for undercover)
      # if: ${{ matrix.emacs_version == env.coveralls_emacs_version }}
      env:
        COVERALLS_FLAG_NAME: Emacs ${{ matrix.emacs_version }}
        COVERALLS_PARALLEL: 1
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      run: |
        eldev -s -dtT test
  finalize:
    runs-on: ubuntu-latest
    if: always()
    needs: test
    steps:
    - name: Finalize Coveralls
      run: |
        curl "https://coveralls.io/webhook?repo_name=$GITHUB_REPOSITORY&repo_token=${{ secrets.GITHUB_TOKEN }}" -d "payload[build_num]=$GITHUB_RUN_NUMBER&payload[status]=done"
